# Pythorch Excercise 1
https://colab.research.google.com/github/YutaroOgawa/pytorch_tutorials_jp/blob/main/notebook/1_Learning%20PyTorch/1_1_tensor_tutorial_jp.ipynb#scrollTo=x9tnynuYAMR_

## Tensors

In [5]:
%matplotlib inline

In [6]:
from __future__ import print_function
import torch

In [7]:
# 初期化されてない行列
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [8]:
# 乱数生成
x = torch.rand(5, 3)
print(x)

tensor([[0.9182, 0.6134, 0.8398],
        [0.9615, 0.0767, 0.7013],
        [0.3744, 0.0975, 0.1029],
        [0.1049, 0.4540, 0.4598],
        [0.6593, 0.6661, 0.9789]])


In [9]:
# long 0
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [10]:
# 数値の指定
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [11]:
# テンソルのコピー
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.9457, -0.3243, -1.3101],
        [ 1.2806, -0.4802, -0.2519],
        [-0.2237, -2.3527, -1.5208],
        [-1.0572, -0.0473, -0.4153],
        [-1.2172,  0.5944, -0.0183]])


In [12]:
print(x.size())

torch.Size([5, 3])


In [13]:
type(x)

torch.Tensor

In [3]:
import numpy as np
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
np.array([])

array([], dtype=float64)